version: 2.1

jobs:
  build_and_push:
    machine: # Utilise une machine virtuelle complète
      enabled: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t nodetest:latest .
      - run:
          name: Test Docker image
          command: |
            docker run -d --name nodetestcontainer -p 8080:80 nodetest
            sleep 5 # Donne un peu de temps au conteneur pour démarrer
            curl --retry 10 --retry-delay 5 -v http://localhost:8080
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag nodetest:latest $DOCKERHUB_USERNAME/nodetest:latest
            docker push $DOCKERHUB_USERNAME/nodetest:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push

